CREATE TABLE USUARIO(
    ID SERIAL PRIMARY KEY,
    NOME_COMPLETO VARCHAR(90),
    LOGIN_ACESSO VARCHAR(90),
    EMAIL VARCHAR(50),
    SENHA_ACESSO VARCHAR(150),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE LOCALIZACAO (
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(80),
    TIPO INTEGER DEFAULT 0,
    ID_PAI INTEGER
);

CREATE TABLE BENS(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(70),
    TIPO INTEGER DEFAULT 0,
    PLACA VARCHAR(10),
    LOCALIZACAO INTEGER
);

CREATE TABLE FORNECEDORES(
    ID SERIAL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(60),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE ITEM(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(60),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE FORMAS_PAGAMENTO(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(50)
);

CREATE TABLE CONTAS_CORRENTES(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(60),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE CONTAS_CORRENTES_MOVIMENTO(
    ID SERIAL PRIMARY KEY,
    VALOR NUMERIC(15,6) NOT NULL,
    TIPO_MOVIMENTACAO INTEGER DEFAULT 0,
    DIRECAO INTEGER DEFAULT 0
);

CREATE TABLE COMPRAS(
    ID SERIAL PRIMARY KEY,
    DATA TIMESTAMP,
    VALOR NUMERIC(15,6),
    FORNECEDOR INTEGER REFERENCES FORNECEDORES(ID),
    PARCELAS INTEGER
);

CREATE TABLE COMPRAS_ITENS(
    ID SERIAL PRIMARY KEY,
    ID_COMPRA INTEGER REFERENCES COMPRAS(ID),
    ITEM INTEGER REFERENCES ITEM(ID),
    QUANTIDADE NUMERIC(15,6),
    UNITARIO NUMERIC(15,6),
    TOTAL NUMERIC(15,6)
);

CREATE TABLE CONTAS_PAGAR(
    ID SERIAL PRIMARY KEY,
    FORNECEDOR INTEGER REFERENCES FORNECEDORES(ID),
    VALOR NUMERIC(15,6),
    PARCELA INTEGER,
    PAGO BOOLEAN DEFAULT FALSE
);

CREATE TABLE CONTAS_PAGAR_PAGAMENTOS(
    ID sERIAL PRIMARY KEY,
    ID_CONTAS_PAGAR INTEGER REFERENCES CONTAS_PAGAR(ID),
    VALOR_PAGO NUMERIC(15,6) NOT NULL,
    PARCELA INTEGER,
    FORMA_PAGAMENTO INTEGER REFERENCES FORMAS_PAGAMENTO(ID),
    ID_MOVIMENTACAO_CONTA INTEGER REFERENCES CONTAS_CORRENTES_MOVIMENTO(ID)
);